name: TruffleHog Scan

on:
  push:
    branches:
      - '*' # Adjust this based on your branch name

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Install any dependencies here, e.g., TruffleHog
        # Example: pip install trufflehog
        pip install --upgrade trufflehog
    - name: Run TruffleHog scan
      id: trufflehog
      run: |
        # Run TruffleHog scan
        trufflehog --no-entropy .
    - name: Save TruffleHog scan results
      if: always()
      run: |
        # Save TruffleHog scan results to a file
        trufflehog --entropy all . --json > trufflehog_results.json
        echo "::set-output name=results::trufflehog_results.json"
    - name: Check for issues and prevent further actions
      if: steps.trufflehog.outputs.results
      run: |
        if [ -s "trufflehog_results.json" ]; then
          git config user.email "aabeigh@hotmail.com"
          git config user.name "aabeigh"
          git revert HEAD --no-edit
          git push origin HEAD
          echo "TruffleHog found issues. Further actions are prevented."
          exit 1
        else
          echo "TruffleHog found no issues. No further actions."
        fi
